/**
 * Shario REST API
 * API for share-thread-filter REST Server
 *
 * OpenAPI spec version: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SharioRestApi) {
      root.SharioRestApi = {};
    }
    root.SharioRestApi.LoginInfo = factory(root.SharioRestApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The LoginInfo model module.
   * @module model/LoginInfo
   * @version 0.0.0
   */

  /**
   * Constructs a new <code>LoginInfo</code>.
   * @alias module:model/LoginInfo
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>LoginInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LoginInfo} obj Optional instance to populate.
   * @return {module:model/LoginInfo} The populated <code>LoginInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('user')) {
        obj['user'] = ApiClient.convertToType(data['user'], 'String');
      }
      if (data.hasOwnProperty('pass')) {
        obj['pass'] = ApiClient.convertToType(data['pass'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} user
   */
  exports.prototype['user'] = undefined;
  /**
   * @member {String} pass
   */
  exports.prototype['pass'] = undefined;



  return exports;
}));


