/**
 * Shario REST API
 * API for share-thread-filter REST Server
 *
 * OpenAPI spec version: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Post'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Post'));
  } else {
    // Browser globals (root is window)
    if (!root.SharioRestApi) {
      root.SharioRestApi = {};
    }
    root.SharioRestApi.Thread = factory(root.SharioRestApi.ApiClient, root.SharioRestApi.Post);
  }
}(this, function(ApiClient, Post) {
  'use strict';




  /**
   * The Thread model module.
   * @module model/Thread
   * @version 0.0.0
   */

  /**
   * Constructs a new <code>Thread</code>.
   * @alias module:model/Thread
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>Thread</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Thread} obj Optional instance to populate.
   * @return {module:model/Thread} The populated <code>Thread</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('no')) {
        obj['no'] = ApiClient.convertToType(data['no'], 'Number');
      }
      if (data.hasOwnProperty('com')) {
        obj['com'] = ApiClient.convertToType(data['com'], 'String');
      }
      if (data.hasOwnProperty('filename')) {
        obj['filename'] = ApiClient.convertToType(data['filename'], 'String');
      }
      if (data.hasOwnProperty('ext')) {
        obj['ext'] = ApiClient.convertToType(data['ext'], 'String');
      }
      if (data.hasOwnProperty('pub_date')) {
        obj['pub_date'] = ApiClient.convertToType(data['pub_date'], 'String');
      }
      if (data.hasOwnProperty('posts')) {
        obj['posts'] = ApiClient.convertToType(data['posts'], [Post]);
      }
    }
    return obj;
  }

  /**
   * @member {Number} no
   */
  exports.prototype['no'] = undefined;
  /**
   * @member {String} com
   */
  exports.prototype['com'] = undefined;
  /**
   * @member {String} filename
   */
  exports.prototype['filename'] = undefined;
  /**
   * @member {String} ext
   */
  exports.prototype['ext'] = undefined;
  /**
   * @member {String} pub_date
   */
  exports.prototype['pub_date'] = undefined;
  /**
   * @member {Array.<module:model/Post>} posts
   */
  exports.prototype['posts'] = undefined;



  return exports;
}));


