/**
 * Shario REST API
 * API for share-thread-filter REST Server
 *
 * OpenAPI spec version: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Thread'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Thread'));
  } else {
    // Browser globals (root is window)
    if (!root.SharioRestApi) {
      root.SharioRestApi = {};
    }
    root.SharioRestApi.Threads = factory(root.SharioRestApi.ApiClient, root.SharioRestApi.Thread);
  }
}(this, function(ApiClient, Thread) {
  'use strict';




  /**
   * The Threads model module.
   * @module model/Threads
   * @version 0.0.0
   */

  /**
   * Constructs a new <code>Threads</code>.
   * @alias module:model/Threads
   * @class
   * @extends Array
   */
  var exports = function() {
    var _this = this;
    _this = new Array();
    Object.setPrototypeOf(_this, exports);

    return _this;
  };

  /**
   * Constructs a <code>Threads</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Threads} obj Optional instance to populate.
   * @return {module:model/Threads} The populated <code>Threads</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      ApiClient.constructFromObject(data, obj, Thread);

    }
    return obj;
  }




  return exports;
}));


